# === Runtime Stage ===
FROM eclipse-temurin:17-jre-slim
WORKDIR /app

# context가 swiftpay-api/이므로 그대로 참조 가능
COPY swiftpay-api/build/libs/swiftpay-api-*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
