# === Runtime Stage ===
FROM eclipse-temurin:17-jre-slim
WORKDIR /app

# Jenkins에서 빌드한 JAR을 Docker 이미지로 복사
COPY build/libs/swiftpay-api-*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
