spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/swiftpay
    username: ${DB_USERNAME:swiftpay}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

hmac:
  secret: ${HMAC_SECRET}

logging:
  level:
    root: INFO
    com.ngyu.swiftpay: INFO
